### ISSUE TITLE
Could not fetch node list from autocluster_aws: no_configured_tags

### ISSUE THREAD

**Issue by giovannialbero1992** [aweber/rabbitmq-autocluster#130]
I'm using 0.6.1 release with aws backend and I've pasted into my rabbitmq.config the same documentation's example.
```
[
  {rabbit, [
    {log_levels, [{autocluster, info}, {connection, info}]}
  ]},
  {autocluster, [
    {backend, aws},
    {aws_ec2_tags, [{"region", "us-west-2"}, {"service", "rabbitmq"}]},
    {aws_ec2_region, "us-east-1"},
    {aws_access_key, "AKIDEXAMPLE"},
    {aws_secret_key, "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY"}
  ]}
].
```
Now when I restart rabbitmq-server into log appears `Could not fetch node list from autocluster_aws: no_configured_tags` .

can it be a feature not supported by plugin's version?

**Comment by michaelklishin** [comment]
Given that e.g. https://github.com/aweber/rabbitmq-autocluster/commit/15743464c53ebfeda163477629584838931d619a is only in master, I'd think so.

**Comment by giovannialbero1992** [comment]
When will you release a new version? for the moment I must compile plugin from master? (but the build in master is failed)

**Comment by michaelklishin** [comment]
I cannot comment on "a build in master failed" because you haven't provided any details (e.g. what RabbitMQ version you are trying to build against).

I don't produce releases but given that we can secure @gmr's approval on a few pull requests, team RabbitMQ hopes to spend some time on this plugin to get it shape in the next few months. Unfortunately I can't make any promises.

**Comment by michaelklishin** [comment]
Also, as of RabbitMQ 3.7.0 which will be out in the next couple of months this plugin will become a collection of peer discovery interface implementations (such as AWS or etcd2).
