### ISSUE TITLE
RabbitMQ crashes on startup with DNS backend

### ISSUE THREAD

**Issue by Draiken** [aweber/rabbitmq-autocluster#33]
Hi there, I've been trying to use this plugin but have not been able to get it working or figure out the cause of the issue :(

I am using the release version `0.4.1` with RabbitMQ version `3.5.6`

The environment variables assigned are:

    AUTOCLUSTER_TYPE=dns
    AUTOCLUSTER_HOST=myhost

The error log from rabbitmq is the following:
```
Error description:
   {could_not_start,rabbit,
       {{case_clause,[]},
        [{autocluster,ensure_registered,2,
             [{file,"src/autocluster.erl"},{line,97}]},
         {autocluster,init,0,[{file,"src/autocluster.erl"},{line,27}]},
         {rabbit,'-run_step/2-lc$^1/1-1-',1,[]},
         {rabbit,run_step,2,[]},
         {rabbit,'-run_boot_steps/1-lc$^0/1-0-',1,[]},
         {rabbit,run_boot_steps,1,[]},
         {rabbit,start,2,[]},
         {application_master,start_it_old,4,
             [{file,"application_master.erl"},{line,273}]}]}}
```

At first I thought it was because the DNS query was failing. I then went into the container and ran an erlang shell, tried using `inet_res:lookup` and it correctly returned the ips.

I've tried adding the explicit logging configuration to RabbitMQ to see if I had a better error message to give me any clues on what's happening but it didn't show anything additional.

Please let me know if you need any additional information

**Comment by gmr** [comment]
That's pretty odd, as it would imply that the module is returning ``[]`` instead of ``{ok, []}`` and I don't see how that can happen. I'm trying to replicate...

**Comment by Draiken** [comment]
I finally found the problem. The problem was on my end :(

To give some background, we're using Kubernetes on the Google Cloud, and they have something called "headless services" which gathers endpoints and can be DNS queried returning the A records for those ips, but unfortunately we don't have the reverse lookup for the IPs.

Because of the that the `inet_res:gethostbyaddr` is giving an error, but I'm not sure why the error doesn't show up anywhere on the stack traces, logs, etc. since I'm not very familiar with Erlang.

**Comment by gmr** [comment]
Thanks for the update, that looks like I can get more meaningful logging in with this info.

**Comment by dhart-alldigital** [comment]
Encountering the same problem trying to use autocluster within kubernetes.  Were you able to overcome this issue?

**Comment by Draiken** [comment]
No, I decided to manually build the clustering logic since I could not get `gethostbyaddr` to return the pod's IP address since I assumed that was the reason autocluster was not working.

Sorry I can't be of much help.

**Comment by dhart-alldigital** [comment]
You were definitely of help @Draiken, you helped me look in the right direction.

My setup is slightly different, I'm running kubernetes within AWS instead of GCE, and not running headless.  But the underlying problem seems to be the same:  `net_res:gethostbyname("rabbitmq")` returns the correct ip of the container, but the problem is that `inet_res:gethostbyaddr` for the same ip resolves to the AWS EC2 host instance rather than the rabbitmq docker container.

I switched from DNS to ETCD to see if that was any different, but the same issue applies.  I then tried manually clustering but rabbitmq needs the hostname of its peers, which without a kubernetes service creating for each pod (and defeating the purpose of a replication controller) its not possible (tried using a headless service but encountered the same problem).

So seeing as I now already have etcd deployed, I modified my pods to record the host and ip in etcd on the postStart lifecycle event, and tear it down on postStop.  I then modified my rabbitmq startup script to read all entries from etcd, and add to /etc/hosts.  Now that the peer hosts are known, the etcd mode of this auto cluster works fine, the only change I needed to make was to remove an extra '/' character in the retrieval of the NodeName.

**Comment by gmr** [comment]
Thanks for the detailed analysis and results here. Sorry for the troubles!

**Comment by aequitas** [comment]
I am running into this issue as well using autocluster in a EC2 environment with autoscaling groups. Reverse DNS does not match the hostname as we don't use EC2 hostnames and have no control over the reverse DNS as we use Route53.

Would it be possible to find a solution for this? 

Also could you please make this fail with an error message more indicative of the problem?
