### ISSUE TITLE
Distribute ez package directly

### ISSUE THREAD

**Issue by scalp42** [aweber/rabbitmq-autocluster#35]
Currently, there's no way to get the plugin in the `.ez` format directly.

Any plans to make them available on the community site?

**Comment by gmr** [comment]
Actually, you can, I have them built and available at:

    https://github.com/aweber/rabbitmq-autocluster/releases

**Comment by michaelklishin** [comment]
If by "community site" you mean [RabbitMQ Community Plugins](http://www.rabbitmq.com/community-plugins.html), that page is controlled by our team.

The only reason why this excellent plugin by @gmr isn't listed there because it wasn't 3.6.0-ready by the time we had to release it. It will be listed there once Gavin tells us it's time.
